spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: blog
      username: root
      password: example
      uri: mongodb://root:example@localhost:27017/?authSource=admin&authMechanism=SCRAM-SHA-1